services:
  nextjs:
    image: node:20-buster
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./nextjs:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    
  nestjs:
    image: node:20-buster
    tty: true
    ports:
      - '3001:3000'
    volumes:
      - ./nestjs:/app
    working_dir: /app
    command: bash -c "npm install && npm run start:dev"
    networks:
      - backend

  db:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_HOST=${DB_ROOT_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - '3307:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - backend

volumes:
  mysqldata:

networks:
  backend: